{application,grpc_prometheus,
             [{applications,[kernel,stdlib,elixir,logger,prometheus,
                             prometheus_ex]},
              {description,"Prometheus interceptor for gRPC"},
              {modules,['Elixir.GRPCPrometheus',
                        'Elixir.GRPCPrometheus.ClientInterceptor',
                        'Elixir.GRPCPrometheus.ClientInterceptor.Config',
                        'Elixir.GRPCPrometheus.ServerInterceptor',
                        'Elixir.GRPCPrometheus.ServerInterceptor.Config']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
