{application,libcluster,
             [{applications,[kernel,stdlib,elixir,logger,inets,jason,crypto,
                             ssl]},
              {description,"Automatic Erlang cluster formation and management for Elixir/Erlang applications"},
              {modules,['Elixir.Cluster.Logger','Elixir.Cluster.Strategy',
                        'Elixir.Cluster.Strategy.DNSPoll',
                        'Elixir.Cluster.Strategy.Epmd',
                        'Elixir.Cluster.Strategy.ErlangHosts',
                        'Elixir.Cluster.Strategy.Gossip',
                        'Elixir.Cluster.Strategy.Kubernetes',
                        'Elixir.Cluster.Strategy.Kubernetes.DNS',
                        'Elixir.Cluster.Strategy.Kubernetes.DNSSRV',
                        'Elixir.Cluster.Strategy.Rancher',
                        'Elixir.Cluster.Strategy.State',
                        'Elixir.Cluster.Supervisor']},
              {registered,[]},
              {vsn,"3.2.1"}]}.
