name: Astreu CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [21.x, 22.x, 23.x]
        elixir: [1.10.x, 1.11.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
        otp-version: ${{matrix.otp}} # Define the OTP version [required]
        experimental-otp: true

    - name: Install dependencies
      run: |
        mix deps.clean --all
        mix deps.get

    - name: Check format
      run: mix format --check-formatted
    - name: Run tests
      run: mix test