name: Astreu Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    name: Build and Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [23.x]
        elixir: [1.11.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
        otp-version: ${{matrix.otp}} # Define the OTP version [required]
        experimental-otp: true

    - name: Install dependencies
      run: |
        mix deps.clean --all
        mix deps.get

    - name: Check format
      run: mix format --check-formatted
      
    - name: Run tests
      run: mix test
  
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: docker.pkg.github.com/eigr/astreu/astreu
        tags: ["0.1.2"]
        tag_with_sha: true
        tag_with_ref: true